### ISSUE TITLE
stringtoslug "self"

### ISSUE THREAD

**Issue by appel** [leocaseiro/jQuery-Plugin-stringToSlug#17]
First off, awesome plugin, thank you for writing it!

I'm trying to have a live slug input field where a user can type anything and have the string automatically _stringToSlug_-ified. It works, but only with `focus` `blur` `change` events. I would like it to be a little more realtime, so that when a user hits Enter to submit the form the changes are applied. Plus, it's nice visual feedback for the user, too, having the value automatically updated to reflect what the slug will look like.

However, using `keypress`, `keyup` and/or `keydown` as events makes it pretty much unusable. For starters, the plugin trims trailing spaces, so it never gets to replace spaces for dashes. Also, text selection in the input is no longer possible.

I didn't see this particular scenario in the examples. Is it possible?

**Comment by leocaseiro** [comment]
Hi @appel, you'd like to slug an input while user is typing? So you won't need to save the string, only the slugged?

Well, you can lock spaces for typing with the follow code:

```javascript
$("#StreamUrl").keydown(function (e) {
     if (e.keyCode == 32) { // space key 
       $(this).val($(this).val() + ""); // remove spaces
       return false; // return false to prevent space from being added
     }
});
```

**Comment by appel** [comment]
That did it, thanks!
