### ISSUE TITLE
Can't get the 'space' option to work when left empty

### ISSUE THREAD

**Issue by appel** [leocaseiro/jQuery-Plugin-stringToSlug#18]
I would like to have no spaces and no separators in my output, but it seems `space: ''` doesn't do the trick.

See [this jsfiddle](https://jsfiddle.net/appel/dmznLhL6/) and type 'Led Zeppelin' to see what I mean. I'm using version 2.0.2.

Expected:
`ledzeppelin`

Result:
`led-zeppelin`

Thanks in advance for your time!

Edit: I've used this workaround for now: `replace: /[ ]/gi`

**Comment by leocaseiro** [comment]
Hi @appel,

You can use the callback function to remove spaces.

Set `space: ' '` and than run on the callback, you can replace the spaces with regexp:

```javascript
$(document).ready( function() {
    $('[type="text"]').stringToSlug({
        space: ' ',
        callback: function(text) {
        		var nospaces = text.replace(/\s/g, '');
            $('#permalink').text(nospaces);
        }
    });
});
```

here's the updated  [jsfiddle])https://jsfiddle.net/f0gu725n/1/)

**Comment by appel** [comment]
Works perfectly! Just out of curiosity, what are potential issues with the workaround I posted earlier: `replace: /[ ]/gi`?

**Comment by leocaseiro** [comment]
Hi @appel, 

I'm glad it worked out or you.

The `replace` is used to remove stuff you don't need.

I set this in the code, because I needed to remove what was between parentheses for a library, but you are right. It should have a `replaceTo`, though.
