### ISSUE TITLE
Use Grunt to build, Bower to publish and manage library and Karma to test your source

### ISSUE THREAD

**Issue by hilios** [leocaseiro/jQuery-Plugin-stringToSlug#8]
If you accepts my suggestion would be great if you manage to:

1. Use [Grunt](http://gruntjs.com/) to automatically manage your build and release workflow;
2. Publish your package to [Bower](http://bower.io/) and manage your internal jQuery dependencies as well;
3. Use [Karma](http://karma-runner.github.io/) runner to run your test and implement a TDD workflow.

This _suggestion_ is what I see as the market best practices, if you need any assistance count on me

**Comment by leocaseiro** [comment]
I'm using Gulp instead of Grunt, but thank you for your advice.
